### ISSUE TITLE
I'm literally confused. The name of files are different from the names of the themes you wrote above the preview images.

### ISSUE THREAD

**Issue by samiternity** [bunnywaffle/GIMP-3-Themes#2]

**Comment by bunnywaffle** [comment]
Sorry, I didn't explain it more clearly. Download the [GIMP-3-Themes-main.rar] file through this link, extract the file, and paste the extracted file into the gimp theme folder. 

Download Link: https://github.com/sujeet-project/GIMP-3-Themes/releases/tag/Themes

**Comment by bunnywaffle** [comment]
Clearfy the process
