### ISSUE TITLE
.css Not working

### ISSUE THREAD

**Issue by saltsoftdrink** [bunnywaffle/GIMP-3-Themes#3]
Why css is not working on latest GIMP if I click on Affinity Theme it gives me default light theme this problem is with all theme. If I'am doing something wrong please make a proper _How To Install_ Section

**Comment by bunnywaffle** [comment]
Sorry, I didn't explain it more clearly. Download the [GIMP-3-Themes-main.rar] file through this link, extract the file, and paste the extracted file into the gimp theme folder. 

Download Link: https://github.com/sujeet-project/GIMP-3-Themes/releases/tag/Themes
